workspace:
  base: /code

pipeline:
  publish-build:
    image: plugins/docker
    repo: nossas/bonde-apis
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    group: builder
    tags:
      - builder
    when:
      status: success
      event: [push, tag]
  
  accounts-staging-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: apis/accounts
    group: deploying
    docker_image: nossas/bonde-apis:builder
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      event: [push]

  payments-staging-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: apis/payments
    group: deploying
    docker_image: nossas/bonde-apis:builder
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      event: [push]

  notifications-staging-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: apis/notifications
    group: deploying
    docker_image: nossas/bonde-apis:builder
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      event: [push]

  activists-staging-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: apis/activists
    group: deploying
    docker_image: nossas/bonde-apis:builder
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      event: [push]

  domains-staging-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: apis/domains
    group: deploying
    docker_image: nossas/bonde-apis:builder
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      event: [push]

  accounts-production-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: apis/accounts
    group: deploying
    docker_image: nossas/bonde-apis:builder
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      event: [tag]

  payments-production-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: apis/payments
    group: deploying
    docker_image: nossas/bonde-apis:builder
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      event: [tag]

  notifications-production-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: apis/notifications
    group: deploying
    docker_image: nossas/bonde-apis:builder
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      event: [tag]

  activists-production-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: apis/activists
    group: deploying
    docker_image: nossas/bonde-apis:builder
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      event: [tag]