services:
  an-web:
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    image: nossas/bonde-an-web-fastapi:feature-webhook-an
    command: uvicorn main:app --host 0.0.0.0 --port 80
    ports:
      - "8000:80"
    env_file:
      - ./.env
    