services:
  cli:
    image: nossas/bonde-an
    build: .
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=123fdsafdsa
      - DATABASE_URL=postgres://localhost:5476/
    command: an/cli.py normalize --community 1 --action donation