x-cli-template:
  &cli-template
    image: nossas/bonde-action-network:latest
    build: 
      context: .
      args:
        GOOGLE_APPLICATION_CONTENT: ${GOOGLE_APPLICATION_CONTENT}
    env_file: .env
    pull_policy: always
    command: python an/cli.py

services:
  cli:
    <<: *cli-template
    command: python an/cli.py
  
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    env_file: .env
    pull_policy: always
    command: python an-webhook/main.py