FROM python:3.10
# RUN apk --update --no-cache add musl-dev linux-headers g++ build-base \
#     postgresql-dev \
#     gcc
RUN mkdir /app

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends software-properties-common gcc zlib1g-dev python3.8-dev \
    libjemalloc-dev libboost-dev \
    libboost-filesystem-dev \
    libboost-system-dev \
    libboost-regex-dev \
    python-dev \
    autoconf \
    flex \
    bison

COPY requirements* /app/

RUN pip install -r requirements-web.txt

RUN ls /

COPY . /app

RUN ls

RUN ls /app