table:
  name: community_settings
  schema: public
object_relationships:
- name: community
  using:
    foreign_key_constraint_on: community_id
select_permissions:
- permission:
    columns:
    - community_id
    - id
    - name
    - settings
    - version
    filter:
      community:
        community_users:
          user_id:
            _eq: X-Hasura-User-Id
  role: user
update_permissions:
- permission:
    check: null
    columns:
    - name
    - settings
    - version
    filter:
      community:
        community_users:
          user_id:
            _eq: X-Hasura-User-Id
  role: user
