name: Hasura migration
on:
  push:
    branches:
      - "release/*"
      - "feature/*"
      - "hotfix/*"
    paths:
      - "migrations/**"
jobs:
  hasura-migration:
    name: Hasura migration
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Apply hasura migrations
        uses: tibotiber/hasura-action@master
        with:
          args: migrate apply --database-name=default
        env:
          HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
          HASURA_WORKDIR: migrations

  hasura-metadata:
    needs: hasura-migration
    name: Hasura metadata
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Apply hasura metadata
        uses: tibotiber/hasura-action@master
        with:
          args: metadata apply
        env:
          HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
          HASURA_WORKDIR: migrations
