name: Publish remote schemas API images
on:
  push:
    branches:
      - "release/*"
      - "feature/*"
      - "hotfix/*"
    tags:
      - v*
    # paths:
    #   - "packages/**"
    #   - "utils/**"
    #   - "package.json"
    #   - "Dockerfile"
    #   - "tsconfig.json"
    #   - "pnpm-*"
jobs:
  tests:
    name: Tests for all apis and libs
    uses: ./tests.yml

  build:
    name: Build apis endpoints
    uses: ./build.yml
    # with:
    #   environment: staging
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
