name: Publish Action Network CLI images
on:
  push:
    branches:
      - "release/*"
      - "feature/*"
      - "hotfix/*"
    tags:
      - v*
    paths:
      - "action-network/cli/**"
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      GOOGLE_APPLICATION_CONTENT:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create Google Credentials JSON
      #   id: create-json
      #   uses: jsdaniell/create-json@1.1.2
      #   with:
      #     name: "gac.json"
      #     json: ${{ secrets.GOOGLE_APPLICATION_CONTENT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./action-network
          push: true
          tags: ghcr.io/nossas/bonde-action-network:latest
          build-args: |
            GOOGLE_APPLICATION_CONTENT=${{ secrets.GOOGLE_APPLICATION_CONTENT }}

      # - name: Build and Publish latest Github Container image
      #   uses: VaultVulp/gp-docker-action@1.0.1
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
      #     image-name: nossas/bonde-action-network # Provide only Docker image name, tag will be automatically set to latest
      #     image-tag: latest
